name = "Package0"
uuid = "0cb0ffc4-12f6-4f88-94c2-a472c78c3076"
authors = ["MatMaz5 <matthiasmazet@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Revise = "3.6.2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
